sudo: required
services:
    - docker
before_install:
    - docker build -t mukiza13/client -f ./client/Dockerfile.dev ./client
scripts:
    - docker run -e CI=true mukiza13/client npm run test -- --coverage
after_success:
    - docker build $DOCKER_ID/multi-client ./client
    - docker build $DOCKER_ID/multi-nginx ./nginx
    - docker build $DOCKER_ID/multi-server ./server
    - docker build $DOCKER_ID/multi-worker ./worker
    #Login to docker hub
    - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
    #Push apps images to docker 
    - docker push $DOCKER_ID/multi-client
    - docker push $DOCKER_ID/multi-nginx
    - docker push $DOCKER_ID/multi-server
    - docker push $DOCKER_ID/multi-worker
