sudo: required
services:
    - docker
before_install:
    - docker build -t mukiza13/client -f ./client/Dockerfile.dev ./client
scripts:
    - docker run -e CI=true mukiza13/client npm run test -- --coverage
after_success:
    - docker build mukiza13/multi-client ./client
    - docker build mukiza13/multi-nginx ./nginx
    - docker build mukiza13/multi-server ./server
    - docker build mukiza13/multi-worker ./worker
    #Login to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push images to docker hub
    - docker push mukiza13/multi-client
    - docker push mukiza13/multi-nginx
    - docker push mukiza13/multi-server
    - docker push mukiza13/multi-worker
