sudo: required
services:
    - docker
before_install:
    - docker build -t mukiza13/client -f ./client/Dockerfile.dev ./client
scripts:
    - docker run -e CI=true mukiza13/client npm run test -- --coverage
after_success:
    - docker build -t mukiza13/multi-client ./client
    - docker build -t mukiza13/multi-nginx ./nginx
    - docker build -t mukiza13/multi-server ./server
    - docker build -t mukiza13/multi-worker ./worker
    #Login to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push apps images to docker 
    - docker push mukiza13/multi-client
    - docker push mukiza13/multi-nginx
    - docker push mukiza13/multi-server
    - docker push mukiza13/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: base_test
    env: BaseTest-env
    bucket_name: elasticbeanstalk-us-west-2-275267023652
    bucket_path: multi-complex
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
